language: csharp
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - libgc-dev

script:
  - make
  - make clean
